apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: launchpad
spec:
  replicas: 2
  selector:
    matchLabels:
      type: development
  template:
    metadata:
      labels:
        type: development
    spec:
      containers:
        - image: couchbase
          name: cbdb

